### ISSUE TITLE
External contents are not found

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#10]
@serverfire For example, searching "html" should return one result

Subissue of #7 

![screenshot 2015-01-05 09 30 11](https://cloud.githubusercontent.com/assets/3107052/5610815/7f83ef52-94bd-11e4-8501-12393b83baba.png)

![screenshot 2015-01-05 09 27 01](https://cloud.githubusercontent.com/assets/3107052/5610817/837f676c-94bd-11e4-8547-4a976cf0e10f.png)

**Comment by serverfire** [comment]
@libreliodev This is because required fields are not specified.

`site_id`=1  // $wpdb->siteid or 1
`blog_id`=1 // get_current_blog_id()
`post_status`="publish"
`post_type`="<type>" // [post,page,attachment]  It helps in filtering search.  I recommend using post.

**Comment by libreliodev** [comment]
@serverfire Now, this works fine, but the link to cloudsearchdetail is not implemented; clicking on the title displays the search results again. You can test with `[wordpress site]//?s=html`

**Comment by serverfire** [comment]
@libreliodev Alright. Now it's fixed.
But html content should not have DOCTYPE. Or any html beginning tags. Like `html`, `head`, `body`, `title`

**Comment by libreliodev** [comment]
Successfully tested
