### ISSUE TITLE
Use CloudSearch, not php, to highlight search terms

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#12]
@serverfire We have noticed that search terms highlighting is obtained with php functions such as `librelio_wrap_matching`. This might create discrepancies or unexpected results. Please use native CloudSearch highlighting, as documented here: http://docs.aws.amazon.com/cloudsearch/latest/developerguide/highlighting.html

Subissue of #7

**Comment by serverfire** [comment]
@libreliodev Done.

**Comment by libreliodev** [comment]
Successfully tested
