### ISSUE TITLE
Some minor errors occur when using cloudsearchdetail.php

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#13]
@serverfire Can this be fixed?

Subissue of #8 

![screenshot 2015-01-05 11 21 58](https://cloud.githubusercontent.com/assets/3107052/5611913/4686509a-94cd-11e4-83f3-b737c1ca332d.png)

**Comment by serverfire** [comment]
@libreliodev Fixed.

**Comment by libreliodev** [comment]
@serverfire I still have some errors. You can test with `[wordpress site]/cloudsearchdetail.php?waurl=s3%3A%2F%2Flibrelio-europe%2Fwolterskluwer%2Fdroitetpatrimoine%2Ftest.html`

![screenshot 2015-01-06 09 29 17](https://cloud.githubusercontent.com/assets/3107052/5626098/c53e3966-9586-11e4-9156-d5d1f78d4ec0.png)

**Comment by serverfire** [comment]
@libreliodev Please check the result with last change.
For me there's no problem.

**Comment by libreliodev** [comment]
Successfully tested
