### ISSUE TITLE
Replace cloudsearchdetail page with shortcodes

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#14]
- Using shortcode `[librelio]` should display the whole file specified in waurl
- Using shortcodce `[librelio id="foo"]`should display:
 - if file specified is a plist, value of "foo"
 - if file is an html file, content of element with id "foo"
 - if file is an xml file, content of node "foo"

**Comment by serverfire** [comment]
@libreliodev 
From where i should get this shortcode?

**Comment by serverfire** [comment]
Since cloudsearchdetail has only access to GET query `waurl`.
We should change its GET url to have the data of search result to it's Id. Like `cloudsearchdetail.php?id=[entry_id]`.

**Comment by libreliodev** [comment]
@serverfire 

> From where i should get this shortcode?

Short codes will be included when creating the article in wordpress admin

> Since cloudsearchdetail has only access to GET query waurl. We should change its GET url to have the data of search result to it's Id. Like cloudsearchdetail.php?id=[entry_id].

As specified in the title, we should no longer use cloudsearchdetail.

 We do not need to know what the original search was. We just need to be able to display the (partial) content of a file specified by waurl. Have we misunderstood each other?

**Comment by serverfire** [comment]
@libreliodev 
Now i get what the title means.

> Short codes will be included when creating the article in wordpress admin

Ok. The problem is the thing where we called it `cloudsearchdetail` was an external content. So we can't associate it to post creation unless it's not an external content(Created in wordpress admin).

**Comment by libreliodev** [comment]
>> Short codes will be included when creating the article in wordpress admin

> Ok. The problem is the thing where we called it `cloudsearchdetail` was an external content. So we can't associate it to post creation unless it's not an external content(Created in wordpress admin).

Sorry, I don't understand you. Let me write again the way I think it should work
- admin creates new post and includes short code(s) in this page
- when this post is displayed with GET argument `waurl=foo.xml`, short codes are replaced with elements from `foo.xml`

Is there anything wrong in this scenrio?

**Comment by serverfire** [comment]
This would be right if the search result where has `foo.xml` as external content has the id of a post in running wordpress site.

**Comment by libreliodev** [comment]
@serverfire 

> This would be right if the search result where has foo.xml as external content has the id of a post in running wordpress site.

OK, got it. Having the id is certainly not a good idea, because it could change, when updating wordpress, or reinstalling it. I guess admin has no control on this id. Is there a way to use another identifier for the post, such as a name, a tag or something else?

**Comment by serverfire** [comment]
@libreliodev I think the best solution is to have a certain post type for these posts and use post_name as their identifier.
Pros.
1. Collision of post_name will occur only on this post types. 
2. post_name is indexed in mysql. So search time would be `O(log(n))` i think.
And we can call its post type `external content template`.

**Comment by libreliodev** [comment]
@serverfire Brilliant. Thanks.

cc @rhanot @ahazeb

**Comment by serverfire** [comment]
So we can keep `cloudsearchdetail` page and `watemplate` specifies the desired post to show as template post.
Or we can follow wordpress `Permalink` and override as described. Which i don't recommend.

**Comment by libreliodev** [comment]
> So we can keep cloudsearchdetail page and watemplate specifies the desired post to show as template post.

OK, thanks.

**Comment by serverfire** [comment]
@libreliodev Done.
Please update composer and use grunt before testing.
```
cd <path-to-plugin>
composer update
grunt
```

**Comment by libreliodev** [comment]
@serverfire Can you please let me know how to test this:
- create a new post first? What specifications?
- use `watemplate`after? Can you provide an example?

**Comment by serverfire** [comment]
@libreliodev Creating new post is fine. But apparently it should accept a new post_type where we made.
I tested it by modifying mysql data. We can create new issue for supporting templates at add new post.
Then `watemplate` should be Permalink name. Look at attached image.

![screen shot 2015-03-10 at 1 16 55 pm](https://cloud.githubusercontent.com/assets/132761/6572516/fed0d3b4-c727-11e4-877b-b39e609350cb.png)

**Comment by libreliodev** [comment]
@serverfire 

> But apparently it should accept a new post_type where we made.

Sorry, I don't understand this. Is there something special we need to configure?

**Comment by libreliodev** [comment]
@serverfire 

Do we still need to use special post types for templates?

**Comment by serverfire** [comment]
@libreliodev Again sorry for inconvenience. This commit solves the issue.
You can now find it in admin menu. `Librelio External Content Templates`

**Comment by serverfire** [comment]
@libreliodev 
>Do we still need to use special post types for templates?

It's not necessary to have a new post type for this issue.
But It's very nice to separate them from regular posts. And It'll solve post_name Collision issue.

**Comment by libreliodev** [comment]
@serverfire 

> You can now find it in admin menu. `Librelio External Content Templates`

Can you change the menu title to `Librelio Templates`? Also, please make sure it's localizable, as well as all new text elements. And if possible, please change the name of the virtual directory created from `ec_template` to `librelio`

**Comment by libreliodev** [comment]
Successfully tested, using cloudsearchdetail.php?waurl=test.html&watemplate=sommaire and  `[librelio id="test"]`.

Still needs testing for plist and xml

**Comment by serverfire** [comment]
@libreliodev What about changing the name from `ec_template` to `librelio_template`

**Comment by libreliodev** [comment]
@serverfire 

> What about changing the name from ec_template to librelio_template

OK

**Comment by libreliodev** [comment]
Successfully tested, using cloudsearchdetail.php?waurl=test.plist&watemplate=sommaire and [librelio id="FileName"].

Still needs testing with xml

**Comment by serverfire** [comment]
@libreliodev Done.

**Comment by libreliodev** [comment]
@serverfire 

Thanks for changing ec_template.

Just tested xml with `waurl=test.xml&watemplate=sommaire` and `[librelio id="Version"]`but nothing is displayed. Can you let me know if I missed something?

**Comment by serverfire** [comment]
@libreliodev Apparently there's an issue at parsing xml for id. I'll check What's wrong.

**Comment by libreliodev** [comment]
@serverfire 

> Apparently there's an issue at parsing xml for id. 

You do not need to parse xml for id, just find the node.

>> if file is an xml file, content of node "foo"

**Comment by serverfire** [comment]
@libreliodev Finding a node requires a xml parser. I don't understand.
XML part is not clear for me. The way i see it. I can not be treated like HTML content. Can you give me an example?

**Comment by libreliodev** [comment]
@serverfire Let's forget xml for the time being. Many thanks.
