### ISSUE TITLE
Restrict external xml display in articles when file is ending with _.xml or _.plist or _.html

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#15]
This has been discussed in #8, and should be implemented and be configurable in admin. Only certain categories of users should be able to see articles with external xml or plist or html

**Comment by serverfire** [comment]
@libreliodev 
It should also restrict displaying them when searching for these entries.

**Comment by libreliodev** [comment]
@serverfire 

> It should also restrict displaying them when searching for these entries.

I don't think so, since search results only show abstracts.

**Comment by serverfire** [comment]
@libreliodev Alright.

**Comment by serverfire** [comment]
@libreliodev Done.

**Comment by libreliodev** [comment]
@serverfire This does not seem to work for me.

Trying to display `cloudsearchdetail.php?waurl=test_.html&watemplate=sommaire` displays a `not found`error.

Can this be language related issue (`administrator` vs `administrateur`)?

![screenshot 2015-03-11 10 08 33](https://cloud.githubusercontent.com/assets/3107052/6593250/1bf8a0e8-c7d7-11e4-8d26-2bd94f89087d.png)
![screenshot 2015-03-11 10 07 16](https://cloud.githubusercontent.com/assets/3107052/6593251/1c15e068-c7d7-11e4-8fa7-51a4a9cfb92c.png)

**Comment by serverfire** [comment]
@libreliodev 
>Can this be language related issue (administrator vs administrateur)?
I don't think so.

This url sends AccessDenied error.
https://librelio-europe.s3-eu-west-1.amazonaws.com/developer/app1/test_.html

Probably we should test with a file where is allowed to see with the registered aws access key in admin.

**Comment by libreliodev** [comment]
@serverfire 

> Probably we should test with a file where is allowed to see with the registered aws access key in admin.

Oh, yes, of course. 
Sorry about that. Let me check again.

**Comment by libreliodev** [comment]
Successfully tested! 
Thanks and sorry, @serverfire
