### ISSUE TITLE
For security reasons, do not include complete url in waurl arg when displaying external contents

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#16]
In #8, it was specified that a complete url could be used for displaying external contents.

This is obviously not secure enough: we need to specify the authorized website and possibly directory in admin, and specify only folder/filename in url.

**Comment by serverfire** [comment]
@libreliodev Done.
Please set `External Content Prefix` to: `s3://librelio-europe/developer/app1/` for test and use `waurl` to: `test.html`.

**Comment by libreliodev** [comment]
@serverfire 

> Please set External Content Prefix to: s3://librelio-europe/developer/app1/ for test and use waurl to: test.html.

Where should this be done please?

**Comment by serverfire** [comment]
@libreliodev Admin -> Setting -> Librelio -> Setting Button -> External Content Prefix

**Comment by libreliodev** [comment]
@serverfire Setting button is inactive in my version, under Safari

**Comment by serverfire** [comment]
@libreliodev Why? Can you show me console log after clicking on setting button?

**Comment by serverfire** [comment]
@libreliodev Please use `grunt` before you test.
```
composer update
grunt
```

**Comment by libreliodev** [comment]
@serverfire Nothing in console log

![screenshot 2015-03-10 10 55 16](https://cloud.githubusercontent.com/assets/3107052/6572648/073c3476-c714-11e4-80cb-902b4d56700c.png)

**Comment by serverfire** [comment]
Please wait. I have to check What's wrong.

**Comment by serverfire** [comment]
@libreliodev I'm sorry for inconvenience.
I forgot to tell you the correct grunt command for building the new version.
```
grunt build:production
```

**Comment by libreliodev** [comment]
@serverfire 

OK, setting button is now active. Let's test this issue now.

**Comment by libreliodev** [comment]
Successfully tested, using `cloudsearchdetail.php?waurl=test.html&watemplate=sommaire`
