### ISSUE TITLE
After updating the Amazon Web Services Plug In, it's no longer possible to use the Librelio plug-in in admin

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#17]
Error message:

`Fatal error: Uncaught exception 'Aws\Common\Exception\InvalidArgumentException' with message 'A region is required when using Amazon CloudSearch' in [path]/wp-content/plugins/amazon-web-services/vendor/aws/Aws/Common/Client/ClientBuilder.php:377 Stack trace: #0 [path]/wp-content/plugins/amazon-web-services/vendor/aws/Aws/Common/Client/ClientBuilder.php(207): Aws\Common\Client\ClientBuilder->updateConfigFromDescription(Object(Guzzle\Common\Collection)) #1 [path]/wp-content/plugins/amazon-web-services/vendor/aws/Aws/CloudSearch/CloudSearchClient.php(83): Aws\Common\Client\ClientBuilder->build() #2 [path]/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Builder/ServiceBuilder.php(141): Aws\CloudSearch\CloudSearchClient::factory(Array) #3 [path]/wp-content/plugins/librelio/lift-core.php(49): Guzzle\Service\Builder in [path]/wp-content/plugins/amazon-web-services/vendor/aws/Aws/Common/Client/ClientBuilder.php on line 377`

@serverfire Can this be fixed? Do you think we'd better include the AWS library files inside the Librelio Plug-In in order to avoid this?

**Comment by serverfire** [comment]
@libreliodev This was a compatibility issue.
Not a big deal. Last commit fixed it.
> Do you think we'd better include the AWS library files inside the Librelio Plug-In in order to avoid this?

Yes it may avoid this issue. But It's Ok. I don't think It'll happen a lot.

**Comment by libreliodev** [comment]
Successfully tested. Many thanks @serverfire
