### ISSUE TITLE
msginit reports an error

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#18]
This is related to #2.

When running msginit, an arror occurs:

    msginit -i librelio.pot -o librelio-fr_FR.po -l fr_FR
    librelio.pot:30: duplicate message definition...
    librelio.pot:27: ...this is the location of the first definition
    msginit: found 1 fatal error`

@serverfire Can you fix this please?

**Comment by serverfire** [comment]
@libreliodev Fixed.

**Comment by libreliodev** [comment]
Successfully tested. Thanks @serverfire
