### ISSUE TITLE
In certain configurations, search results are not returned from CloudSearch, even if `Override search` has been selected

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#21]
@serverfire Please take a look at the customer site we're working on.
Searching for `Annecy` returns no result, whereas there is an entry with `Annecy`in the index.

**Comment by serverfire** [comment]
@libreliodev Including that CloudSearch is not working. I'll check it.

**Comment by serverfire** [comment]
@libreliodev Fixed!

**Comment by serverfire** [comment]
Currently an unknown error caused from POST request for search.
Apparently this problem is from AWS api. Until they fix it we can use this hack.

Also post_status should have search tag.

**Comment by libreliodev** [comment]
@serverfire 

Can you explain:

> Also post_status should have search tag.

**Comment by serverfire** [comment]
@libreliodev 
`post_status` index field in our cloudsearch domain wasn't have `searchEnabled` property.
I inserted in our shared domain and in plugin schema.

**Comment by libreliodev** [comment]
@serverfire Does it mean that when a new post is created, author should insert a `search``tag`?

**Comment by serverfire** [comment]
@libreliodev No. 
>Also post_status should have search tag.

I was trying to explain why the behavior exist.
Sorry about that.

**Comment by libreliodev** [comment]
@serverfire OK, thanks. So, now, everything is working properly?

**Comment by serverfire** [comment]
@libreliodev I hope so. It's working on my local server.

**Comment by libreliodev** [comment]
@serverfire So, we need to update the current customer's sever?

**Comment by serverfire** [comment]
@libreliodev That's right.
I don't think i have access to server.

**Comment by libreliodev** [comment]
@serverfire 

> I don't think i have access to server. (Upload content)

Admin access has been given to you, which allows you to install extensions, and edit php files for installed extensions

**Comment by serverfire** [comment]
@libreliodev I'm uploading it.

**Comment by serverfire** [comment]
@libreliodev Done

**Comment by libreliodev** [comment]
Successfully tested. Thanks.

**Comment by libreliodev** [comment]
@serverfire 

Sorry, I am reopening this issue: I can still see documents to be synced on the Librelio settings page. Any idea why?

**Comment by serverfire** [comment]
@libreliodev I don't see any documents in sync queue.

**Comment by libreliodev** [comment]
@serverfire You should again see dozens of documents in sync queue

**Comment by serverfire** [comment]
@libreliodev Fixed via 1ff4881

**Comment by libreliodev** [comment]
OK, thanks.
