### ISSUE TITLE
Create script to handle uploaded files to AUT_ folder in S3 directory - Uncompress

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#22]
This script should be either triggered by an http request, or by wordpress-cron at the same time as lift-search updates

As a first step, the script should scan the AUT_ folder on the S3 folder, and uncompress all files

**Comment by serverfire** [comment]
@libreliodev 
Are these files are zip files?
Should we do the rest of procedure one at a time for each file?

**Comment by libreliodev** [comment]
@serverfire 

> Are these files are zip files?

Yes, the original files don't have `.zip`extension, but are zip files

> Should we do the rest of procedure one at a time for each file?

The best option would be to group together all files with the same name (but different extension), and apply the complete script to the set of files.

**Comment by serverfire** [comment]
@libreliodev 
>The best option would be to group together all files with the same name (but different extension), and apply the complete script to this set of files.

To clarify the process.
1. Get the list of files in specified S3 directory.
2. Group zip files as specified and for each group do the rest.

Then each group has a single `[file_name]_toc_.xml` and output is in a single directory named `[file_name]`.

**Comment by libreliodev** [comment]
@serverfire This Is correct

**Comment by serverfire** [comment]
@libreliodev It's almost done. I've to test it. Can you help me creating a test process?
What we need.
1. Access to a s3 bucket for read and write. (For specific directory is ok)
2. A example document for uploading.

Thank you

**Comment by libreliodev** [comment]
@serverfire 

You can use the current customer, and the credentials you already have. The are example files in the AUT_ folder.

**Comment by serverfire** [comment]
@libreliodev Which Bucket and KeyPrefix(<publisher>/<app>)?

**Comment by libreliodev** [comment]
@serverfire See private answer

**Comment by serverfire** [comment]
@libreliodev Done.

Things to do before testing.
```
composer update
grunt build:production
```

And set settings in librelio page.

Move uploaded zip files was not specified to where. So for now it's `AUT_END_`.

**Comment by serverfire** [comment]
run script with
http://[wpsite]/process_s3upload.php

**Comment by libreliodev** [comment]
@serverfire Have you updated the customer's site, or should we do it?

**Comment by serverfire** [comment]
@libreliodev I've Installed it.

**Comment by serverfire** [comment]
@libreliodev Unfortunately i stuck with a syntax error. I can fix it with ftp access to site.

**Comment by libreliodev** [comment]
@serverfire FTP credentials sent to you via private message. Please let us know when we can test.We tried running `http://[wpsite]/process_s3upload.php` but nothing seems to have happened

**Comment by serverfire** [comment]
@libreliodev Ready for testing.

**Comment by libreliodev** [comment]
@serverfire Successfully tested

**Comment by libreliodev** [comment]
@serverfire 

It was specified that 

> This script should be either triggered by an http request, or by wordpress-cron at the same time as lift-search updates

This does not seem to have been implemented. Can you please correct?

**Comment by serverfire** [comment]
@libreliodev I'll setup wordpress-cron after other issues has solved.
