### ISSUE TITLE
Create script to handle uploaded files to AUT_ folder in S3 directory - Rename

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#23]
This is related to #22 .

The second step of the script is to rename all uncompressed files.

This should be done as follows:
- an underscore should be added before all extensions: myfile.ext should become myfile_.ext
- a special file with a special suffix (to be entered in `Librelio Setting`) should be renamed without its suffix and `_toc_.xml` instead. For the "current customer", the special suffix will be  `_sommaire.def`, so `dph-2014-987_sommaire.def`should become `dph-2014-987_toc_.xml`

**Comment by libreliodev** [comment]
@serverfire There is a small bug here: `dph-2014-987_sommaire.def` becomes `dph-2014-987_sommaire_toc_.xml` instead of becoming `dph-2014-987_toc_.xml`

**Comment by serverfire** [comment]
@libreliodev Fixed.

**Comment by libreliodev** [comment]
@serverfire Thanks. Has this been uploaded to client site?

**Comment by serverfire** [comment]
@libreliodev Yes

**Comment by libreliodev** [comment]
@serverfire 

Got an exception

				Exception: The specified key does not exist.
				#0 createException() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Aws/Common/Exception/NamespaceExceptionFactory.php:76
				#1 fromResponse() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Aws/Common/Exception/ExceptionListener.php:55
				#2 onRequestError() :
				#3 call_user_func() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Symfony/Component/EventDispatcher/EventDispatcher.php:164
				#4 doDispatch() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Symfony/Component/EventDispatcher/EventDispatcher.php:53
				#5 dispatch() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Message/Request.php:589
				#6 processResponse() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Message/Request.php:378
				#7 setState() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Message/EntityEnclosingRequest.php:49
				#8 setState() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Curl/CurlMulti.php:303
				#9 processResponse() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Curl/CurlMulti.php:257
				#10 processMessages() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Curl/CurlMulti.php:240
				#11 executeHandles() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Curl/CurlMulti.php:224
				#12 perform() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Curl/CurlMulti.php:111
				#13 send() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Curl/CurlMultiProxy.php:94
				#14 send() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Http/Client.php:284
				#15 send() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Aws/Common/Client/AbstractClient.php:261
				#16 send() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Client.php:136
				#17 execute() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Command/AbstractCommand.php:153
				#18 execute() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Command/AbstractCommand.php:189
				#19 getResult() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Guzzle/Service/Client.php:76
				#20 __call() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/amazon-web-services/vendor/aws/Aws/Common/Client/AbstractClient.php:106
				#21 __call() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/librelio-wp-liftsearch/wp/librelio-external-uploader.php:290
				#22 copyObject() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/librelio-wp-liftsearch/wp/librelio-external-uploader.php:290
				#23 freeDocument() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/librelio-wp-liftsearch/wp/librelio-external-uploader.php:271
				#24 freeBatch() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/librelio-wp-liftsearch/classes/Librelio/DocumentUploader/DocumentUploader.php:83
				#25 freeBatch() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/librelio-wp-liftsearch/classes/Librelio/DocumentUploader/DocumentUploader.php:56
				#26 upload() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/librelio-wp-liftsearch/wp/librelio-external-uploader.php:42
				#27 librelio_external_uploader_upload() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-content/plugins/librelio-wp-liftsearch/lift-core.php:262
				#28 view_project_template() :
				#29 call_user_func_array() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-includes/plugin.php:213
				#30 apply_filters() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-includes/template-loader.php:73
				#31 require_once() /var/www/vhosts/droit-patrimoine.fr/httpdocs/wp-blog-header.php:16
				#32 require() /var/www/vhosts/droit-patrimoine.fr/httpdocs/index.php:17
				Done!

**Comment by libreliodev** [comment]
@serverfire Despite the exception (please fix it), the bug was fixed. Thanks.

**Comment by serverfire** [comment]
@libreliodev Concurrent request to script made this error. I'll ignore this error. Cause it does no harm into process.

**Comment by serverfire** [comment]
@libreliodev Done
