### ISSUE TITLE
Create script to handle uploaded files to AUT_ folder in S3 directory - Parse and index

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#24]
This is related to #22 and #23.

As a third step, the script should parse the toc file identified in #23.

It should parse this file, and create (or update) an index entry in CloudSearch for each TOC entry

Details of the mapping will be specified later.

**Comment by libreliodev** [comment]
@serverfire This does not seem to have been implemented yet. Sorry, mapping has not been specified yet.

**Comment by serverfire** [comment]
@libreliodev Just mapping is remained.

**Comment by libreliodev** [comment]
@serverfire Sorry for the delay.

Here is the mapping we want to implement:
- blog_id:1	
- id: automatic	
- post_author: leave empty
- post_author_name:  leave empty	
- post_content: content of <body>` in html  file
- post_date_gmt: deducted from name of html file; for instance, if name is `1524495072_20141117_txt.html`, date is 201411117, which needs to be converted in relevant format for CloudSearch
- post_name:	name of html file
- post_status: 
- post_title	: `te-title` node in toc_.xml
- post_type: "external"
- resourcename: directory and filename of html file
- site_id: 1	
- taxonomy_category_id: leave empty
- taxonomy_category_label: leave empty
- taxonomy_post_tag_id: leave empty
- taxonomy_post_tag_label: leave empty

Please let us know if you have questions or concerns. Thanks.

**Comment by serverfire** [comment]
@libreliodev How to detect html file? Where used in post_content and post_date_gmt.

**Comment by libreliodev** [comment]
@serverfire 

> How to detect html file? Where used in post_content and post_date_gmt.

Use `target-doc`in `tocentry`. For example with:

	<tocentry tocentry-id="UD-1524495077" tocentry-parent-id="4" order="17" target-doc="1524495077" target-type="internal">

list files starting with `1524495077`, and take the one with extension `html`/

**Comment by serverfire** [comment]
@libreliodev Unfortunately `post_date_gmt` current is an int with unix time-stamp. I think we should use timestamp for date since it does not have much difference. Otherwise we should change schema and send batch for wordpress posts.

**Comment by serverfire** [comment]
@libreliodev Done via ea55014 .
Also couple of bugs has fixed.
- Search in customer site
- extra debug codes removed

**Comment by libreliodev** [comment]
@serverfire 

> Done via ea55014 . And Uploaded.

Thank you very much, will try to test later today

> Unfortunately post_date_gmt current is an int with unix time-stamp. I think we can timestamp for date since it does not have much difference. Otherwise we should change schema and send batch for wordpress posts.

Is this still valid? Is there something we need to do or decide?

**Comment by serverfire** [comment]
@libreliodev 
>Is this still valid? Is there something we need to do or decide?

Nothing needs to be done. Yes I'd like you to know what's goijng on.
If you deside to change it, We're ready to do that.

**Comment by libreliodev** [comment]
@serverfire 

Tested on client site. Seems to work fine.

Got following answer to request. Could this mean that something did not work fine?
```
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
log: string(27) "Subdocument file not found!" string(15) "target-doc=NULL" array(0) { } 
Done!
```

**Comment by serverfire** [comment]
@libreliodev This means could not upload some documents. Because the value of `target-doc` was not found in zip files. No problem.

**Comment by serverfire** [comment]
@libreliodev I see some files produce error from xml entity. `&deg;`. XML parser does not supported. Then whole sub-documents after that will not get uploaded.
You can use `"&#176;"` instead. See
http://www.w3.org/TR/html4/sgml/entities.html

**Comment by libreliodev** [comment]
@serverfire We can probably not change the xml produced by the customer. Can you suggest turnarounds?

**Comment by serverfire** [comment]
@libreliodev One quick solution could be making a fixer in script.
Before it reads the document. 

For example we can replace specific texts with the correct one. `&deg; => &#176;".

**Comment by libreliodev** [comment]
@serverfire Thanks.

Can you please create a new issue for this and describe what needs to be done?

**Comment by serverfire** [comment]
@libreliodev Alright.

Or we can use another parser.
Currently We're using `XMLReader`.

**Comment by libreliodev** [comment]
@serverfire 

> Or we can use another parser.

The may be more "tolerant" parsers, yes. Let's start with this option, I think.

**Comment by serverfire** [comment]
@libreliodev I tried another parser. That also had problem.

Can customer generate xml's html content wrapped in CDATA?

**Comment by libreliodev** [comment]
@serverfire We have no control on customer's xml, which would be very complicated to change

**Comment by serverfire** [comment]
@libreliodev I believe replacing `&` with `&amp;amp;`. Is a practical solution for this case.
Where we have html content in xml.
