### ISSUE TITLE
Create script to handle uploaded files to AUT_ folder in S3 directory - Move

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#25]
This is related to #22, #23 and #24.

As a fourth step, the script should move all files to the appropriate location in the S3 directory.

The toc file should be moved to a directory with the same name as itself, without the _toc_xml suffix.

So, for example, `dph-2014-987_toc_.xml` should be moved to `dph-2014-987`.

All other files should be moved to this folder.

At the end of the script, all files in the AUT_ folder should be moved.

**Comment by libreliodev** [comment]
@serverfire Successfully tested.
Please do not use AUT_END_, just delete the original files

**Comment by serverfire** [comment]
@libreliodev Done.

**Comment by libreliodev** [comment]
@serverfire OK, thanks.
