### ISSUE TITLE
Find alternate solutions when define('ALTERNATE_WP_CRON', true) is needed

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#26]
As discussed in #20, it is sometimes needed to use `define('ALTERNATE_WP_CRON', true)` . This does not seem to be a good practice, as some users will have long response times.

@serverfire Would it be possible to make an http request avery 5 minutes or so from another site to replace this method? What would be the URL to use?

**Comment by serverfire** [comment]
@libreliodev 
>Would it be possible to make an http request avery 5 minutes or so from another site to replace this method?

Yes.
Guide is right here. http://code.tutsplus.com/articles/insights-into-wp-cron-an-introduction-to-scheduling-tasks-in-wordpress--wp-23119
1. Disable internal WP-Cron to execute on page load.
2. Setup a cron function that makes a get request to the wp-cron.php file at regular intervals based on your preference.

>What would be the URL to use?

http://www.yourwebsite.com/wp-cron.php?doing_wp_cron=1

**Comment by libreliodev** [comment]
@serverfire FYI, the client has now disabled `define('ALTERNATE_WP_CRON', true)`, but we have not yet implemented this alternate method;
