### ISSUE TITLE
AUT_folder script: Find pdf if it exists, and move it to root of publication folder

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#27]
This is related to #22, #23,#24, and #25.

In some cases, there is somewhere a pdf called `[foldername].pdf` (which should have been renamed  `[foldername]_.pdf` by the script).

We want this pdf to moved to the root level of the folder.

For example, assuming a folder called `drpat-2014-0232` has been created by the script. If this folder contains drpat-2014-0232_.pdf inside `drpat-2014-0232/bin/2014...`, it should be moved to `drpat-2014-0232`

**Comment by serverfire** [comment]
@libreliodev Issue 27 to 30 are implemented. 
Most likely they changes. :)

**Comment by libreliodev** [comment]
@serverfire Have you already tested with elements previously in `ANT_temp`?

**Comment by serverfire** [comment]
@libreliodev I tested one of the files in ANT_temp. They're not in s3 service now.

**Comment by libreliodev** [comment]
Continued in https://github.com/libreliodev/php/issues/49
