### ISSUE TITLE
AUT_folder script: Find cover if it exists, save it to new format (in 2 versions) and move new files to root of publication folder

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#28]
This is related to #22, #23,#24, and #25 and similar to #27.

In some cases, there is somewhere a jpg called [foldername]-cover.jpg (which should have been renamed [foldername]_.jpg by the script).

We want to create 2 png files from this file, and move them to the root level.
- the first png file should be 300 px high, and should be named [foldername].png
- the second png file should be 1024 px high, and should be name [foldername]_newsstand.png

Then, both png files should be moved to the root level.

For example, assuming a folder called drpat-2014-0232 has been created by the script. If this folder contains drpat-2014-0232-cover_.jpg inside drpat-2014-0232/img/2014..., 2 files should be generated and moved to the root level:
- drpat-2014-0232.png
- drpat-2014-0232_newwstand.png

**Comment by intrications** [comment]
@libreliodev 

I noticed that `drpat-2014-0232_newwstand.png` should be `drpat-2014-0232_newsstand.png` in the final line.

**Comment by libreliodev** [comment]
> I noticed that drpat-2014-0232_newwstand.png should be drpat-2014-0232_newsstand.png in the final line.

Thanks @intrications

**Comment by libreliodev** [comment]
Replaced by https://github.com/libreliodev/php/issues/48
