### ISSUE TITLE
AUT_folder script: generate new entry in "Magazine.plist"

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#29]
This is related to #22, #23,#24, #25, #27 and #28. 

After creating the new folder, if (and only if) it contains a pdf as specified in #27, then add a new entry in `Magazines.plist` (as usual) with this pdf. The name of `Magazines.plist` should be the same as the folder, without any figure or punctuation. 

For example, assuming a folder called `drpat-2014-0232`has been created, the name of the plist to be updated shoud be `drpat.plist`

**Comment by serverfire** [comment]
@libreliodev 
I'm a little confused.
Is this happening for each document? And are they separated from each other?

> The name of Magazines.plist should be the same as the folder, without any figure or punctuation. 

Do you mean there's no change in main Magazines.plist file?

**Comment by libreliodev** [comment]
@serverfire 

> I'm a little confused.

Sorry, that was not clear.

> Is this happening for each document? And are they separated from each other?

Yes

> Do you mean there's no change in main Magazines.plist file?

Actually, the situation with the current customer is similar to the one with the other one for whom we developed https://github.com/libreliodev/javascript/issues/195 . There are 2 différent publications in the app. By the way, this means that we also need to make a small change to #25: see #33.

**Comment by serverfire** [comment]
@libreliodev So is this issue and #30 are editing the same file?

**Comment by libreliodev** [comment]
Continued in https://github.com/libreliodev/php/issues/50
