### ISSUE TITLE
AUT_folder script: generate "toc.plist"

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#30]
This is related to #22, #23,#24, #25, #27,#28 and #29 

In #24, we implemented a process to parse the toc file identified in #23, and create (or update) an index entry in CloudSearch for each TOC entry.

We need to put these elements a plist. The plist should be an array with all articles that have been found.
Each entry should contain:
- Title
- Subtitle (if available)
- The first 200 characters of the article

This plist should be saved as toc.plist at the root level.

**Comment by serverfire** [comment]
@libreliodev I think `Title` is the `te-title` tag in `tocentry`.
What about `Subtitle`?

**Comment by libreliodev** [comment]
@serverfire If there is no obvious answer, leave it empty for the time being

**Comment by libreliodev** [comment]
Continued in https://github.com/libreliodev/php/issues/46
