### ISSUE TITLE
Use a specific folder for each publication

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#33]
This is a small change to #25.

It was speicified that 

> The toc file should be moved to a directory with the same name as itself, without the _toc_xml suffix.

> So, for example, dph-2014-987_toc_.xml should be moved to dph-2014-987.

> All other files should be moved to this folder.

Now what we want is that the toc file is moved to a directory with the same name as itself, without the _toc.xml suffix, inside a directory without figures and punctuation. So, for example, dph-2014-987_toc_.xml should be moved to dph/dph-2014-987

**Comment by serverfire** [comment]
@libreliodev Done.

**Comment by libreliodev** [comment]
@serverfire 

There was a misunderstanding regarding this spec

> Now what we want is that the toc file is moved to a directory with the same name as itself, without the toc.xml suffix, inside a directory without figures and punctuation. So, for example, `dph-2014-987_toc.xml `should be moved to `dph/dph-2014-987`

in our example `dph-2014-987_toc.xml`should not be renamed, it should be put inside `dph/dph-2014-987/`
