### ISSUE TITLE
Links from search no longer work

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#36]
Try for example with `search/Mazzei`in current project.

**Comment by serverfire** [comment]
@libreliodev Do we have to specify a template for each external content? 
Because currently specifying template is necessary.

And also that file is not exists in s3. Maybe it has been deleted.

**Comment by serverfire** [comment]
@libreliodev For this search `search/Mazzei` we may re-upload that document data.
I don't know where they're.

**Comment by libreliodev** [comment]
OK, will be done later

**Comment by libreliodev** [comment]
@serverfire Can you try with `search/plf`?

**Comment by serverfire** [comment]
@libreliodev I've checked it.
The problem is. That they did not uploaded well. We should do it again. 
Also yesterday a bug deleted some of upload files. I don't have them. Sorry, Can you help me with it?

**Comment by libreliodev** [comment]
@serverfire 

> The problem is. That they did not uploaded well. We should do it again. 

I don't understand what you mean. Please elaborate.

> Also yesterday a bug deleted some of upload files. I don't have them. Sorry, Can you help me with it?

Yes, do you know what files you need to restore?

**Comment by serverfire** [comment]
@libreliodev 
>>The problem is. That they did not uploaded well. We should do it again.

>I don't understand what you mean. Please elaborate.

I made few upload execution where does not processed well. I mean files did not uploaded.
So we should do them again for fixing these errors.

>Yes, do you know what files you need to restore?

Doesn't matter. Just the ones you want to test with them.

**Comment by libreliodev** [comment]
@serverfire A few files have been put in AUT_

**Comment by libreliodev** [comment]
Will be checked later in https://github.com/libreliodev/php
