### ISSUE TITLE
Modify script to handle uploaded files to AUT_ folder in S3 directory - Rename

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#38]
This is a modification to #23.

We need to include the publication date according to Librelio specs. As a reminder, according to Librelio specs, files should be named filename_YYYYMMDD (with a final underscore or not, plus extension).

So, the specifications provided in #23 become:

- the date and an underscore should be added before all extensions: `myfile.ext` should become `myfile_YYYYMMDD_.ext`
- a special file with a special suffix (to be entered in Librelio Setting) should be renamed without its suffix and `_toc_YYYYMMDD_.xml` instead. For the "current customer", the special suffix will be `_sommaire.def`, so `dph-2014-987_sommaire.def` should become `dph-2014-987_20140101_toc_.xml `(20140101 is a hypothetical date in this example).

Please note that this will also impact #25. The folder to be created as specified in #25 should now include the date at the end, for example `dph-2014-987_20140101`

**Comment by serverfire** [comment]
@libreliodev 
From where i should parse this date?

**Comment by libreliodev** [comment]
@serverfire 

> From where it should parse this date?

Will be answered later today, thanks.

**Comment by libreliodev** [comment]
@serverfire 

> From where it should parse this date?

You should take the same date as the one specified in https://github.com/libreliodev/wordpress/issues/24#issuecomment-91553157

**Comment by serverfire** [comment]
@libreliodev They're multiple sub-documents. How we can set date for all files with them?

**Comment by libreliodev** [comment]
@serverfire 

> They're multiple sub-documents. How we can set date for all files with them?

OK, good question. I think they are supposed to be all the same. Take the first one.

**Comment by serverfire** [comment]
@libreliodev Also html files already have date. Then it would be duplicate date for them.
I think we should narrow down files with date.

**Comment by libreliodev** [comment]
@serverfire Can you give an example?

**Comment by serverfire** [comment]
@libreliodev In zip file: `2013.120150414000576745.docs` -> FIle `1524834501_20150413_txt_.html`

If we add date to it. Then it's two dates in file name.

**Comment by libreliodev** [comment]
OK, then we should remove `_text_.`

**Comment by serverfire** [comment]
@libreliodev Last commit has uploaded in current using site.
It's uploading one document at a execution.  And moves processed zip files in DONE folder. For now.
