### ISSUE TITLE
Make it possible to include folder name and folder date in short code

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#39]
This is similar to #32. Assuming for example that file is in folder `dph-2014-987_20140101`

- using `[librelio foldername]` should return `dph-2014-987_20140101`
- using `[librelio folderdate]`should return 1/1/2014, formatted depending on the wp/user settings

**Comment by serverfire** [comment]
@libreliodev 
I suggest to supply date format in folderdate attr. Something like this.
`[librelio folderdate="d-m-Y"]`

**Comment by libreliodev** [comment]
@serverfire 

> I suggest to supply date format in folderdate attr.

Great suggestion, thanks.

**Comment by libreliodev** [comment]
@serverfire Can you describe the syntax used for date format?

**Comment by serverfire** [comment]
@libreliodev Syntax is php date syntax. See http://php.net/manual/en/datetime.createfromformat.php
