### ISSUE TITLE
Make it possible to get folder name when iterating in plists

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#40]
In #31, we implemented an iterator method.

We introduced the `item.key`syntax. Thus, when using `item.FileName`, we can get the complete file name from `Magazines.plist`, for example `dph-2015-1001_20150309/dph-2015-1001_20150309.pdf`.

In certain cases, we need to get only the folder name, for example here `dph-2015-1001_20150309`.

This could be done using the syntax `item.FileName.foldername`. 

@serverfire Do you have other syntax suggestions? Can you do this urgently?

**Comment by serverfire** [comment]
@libreliodev A better solution is to have abstract for each procedure.
Instead we can use `foldername(item.FileName)`.
We can use one of existing syntax available. I'll see what's good for this case.

**Comment by libreliodev** [comment]
@serverfire I agree with you, thanks.

**Comment by serverfire** [comment]
@libreliodev Unfortunately i didn't found a good parser or evaluator for our use.
UglifyJS seams to have a good parser. But i wasn't able to find a good port for it in php.
Do you have any suggestions?
For now we only need two feature from javascript language. 
1. Referencing a property from an object. (Variables)
2. Function calls with arguments.

**Comment by libreliodev** [comment]
@serverfire Sorry, I don't have suggestions. But let's keep things as simple as possible in order to go fast.

**Comment by serverfire** [comment]
@libreliodev If this project does not have long development we can follow the original description.
Or i can implement a very simple parser for it.

**Comment by libreliodev** [comment]
@serverfire Yes please, do as simple as possible. If `foldername(item.FileName)`is possible, I agree it's better than `item.FileName.foldername`. But again, the priority is to be fast here.

**Comment by serverfire** [comment]
@libreliodev Done!
See SScript. It's nice!
Example
```
[librelio foreach="document as item"]
[librelio id="item.FileName"]
[librelio id="foldername(item.FileName)"]
___________________________
[librelio endforeach]
```
You can run it using. `cloudsearchdetail.php?waurl=/drpat/drpat.plist&watemplate=[template]`

**Comment by libreliodev** [comment]
Successfully tested.
