### ISSUE TITLE
Display all results from CloudSearch

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#7]
We are going to use CloudSearch to index not only WordPress posts, but also external contents, in HTML format (to start with).

So, the results page should display not only WordPress posts, but also other contents. The following fields, returned by CloudSearch, should be displayed:
- post_title (with highlighting of search terms)
- post_date_gmt (converted to date format, according to user's setings)
- post_content (with highlighting of search terms)

There should be a link on the title, with one of the following destinations:
- if the found element is a WP post, link to the post itself
- if the found element is not a WP post, link to a WP page `cloudsearchdetail.php`(to be created), with a waurl argument given by CloudSearch field `resourcename` and encoded. So, for example, if resourcename returned by CloudSearch is `s3://librelio-europe/doc.html`, link should be `cloudsearchdetail.php?waurl=s3%3A%2F%2Flibrelio-europe%2Fdoc.html`

**Comment by serverfire** [comment]
@libreliodev Done

**Comment by libreliodev** [comment]
@serverfire Please review subissues related to this one

**Comment by libreliodev** [comment]
Successfully tested
