### ISSUE TITLE
Implement cloudsearchdetail.php

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#8]
As introduced in #7, we need a page to display external content in HTML format, stored on the S3 server.

In order to do so, the php script will have to download the external HTML content stored on the S3 server, from the url given by `waurl`, and include it into the page.

**Comment by serverfire** [comment]
@libreliodev Done

**Comment by serverfire** [comment]
Please use `grunt build:production`

**Comment by libreliodev** [comment]
@serverfire I don't see `cloudsearchdetail.php`

**Comment by serverfire** [comment]
@libreliodev `cloudsearchdetail.php` is virtually assigned using `apache mod_rewrite`.

**Comment by libreliodev** [comment]
@serverfire Can you give an example of url that should be used in the front end?

**Comment by libreliodev** [comment]
Anyway, I think we should avoid using `external rules`. See http://wordpress.stackexchange.com/questions/9870/how-do-you-create-a-virtual-page-in-wordpress

**Comment by serverfire** [comment]
`mywordpress.com/cloudsearchdetail.php?waurl=s3%3A%2F%2Flibrelio-europe%2Fdeveloper%2Fwind%2FMagazines.plist`

Let fix NOTICE error. It was off for me.

**Comment by serverfire** [comment]
@libreliodev I think didn't used external rules. It's just a template replacement at including template. 
Since every template can have different view. We can't create a page and expect it would match the site. (Sidebar, Heading, Footer, etc)
We have two choice here.
1. Make a new page completely different. And doesn't change across templates.
2. Give html page as a post. And template takes care of printing it on site.

I've used method two. Because i thought that's is the expected result.

**Comment by libreliodev** [comment]
@serverfire OK, let me test more.

**Comment by libreliodev** [comment]
@serverfire 

> Give html page as a post. And template takes care of printing it on site.

This is fine (except minor errors reported in #13). 

However, I have a question. Is it possible to make this page visible only to certain categories of registered users? Does this require extra development, or is it just a simple setting in the admin?

Thanks.

**Comment by serverfire** [comment]
>  Is it possible to make this page visible only to certain categories of registered users?

Yes

> Does this require extra development, or is it just a simple setting in the admin?

It requires extra development. And we may add admin setting for it.

**Comment by libreliodev** [comment]
Successfully tested
