### ISSUE TITLE
Some minor errors occur when performing search

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#9]
@serverfire Can you please correct this?

Subissue of #7 

![screenshot 2015-01-04 10 40 18](https://cloud.githubusercontent.com/assets/3107052/5610622/ed90da1c-94ba-11e4-8d91-386bb18f1db4.png)

**Comment by serverfire** [comment]
@libreliodev Fixed

**Comment by libreliodev** [comment]
Successfully tested
